### ISSUE TITLE
Gadgetry Transmission doesnt work

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [Pythonic-Rainbow/Big-Bang-Mods#17] opened 2018-08-26 12:10 UTC
**Pack Version:**
Any
 

**Describe your problem(Use human-readable syntax!)**
Gadgetry Transmission is just broken
 

**References(If you know about this issue, Put reference links below. If you don't, ignore this.**
https://minecraft.curseforge.com/projects/gadgetry-transmission?comment=1

**Comment by Pythonic-Rainbow** [comment] 2018-08-26 13:30
@CrankySupertoon01 thanks for your report!  As we know the mod isn't being updated by the mod author, I can do nothing about it. The mod doesn't do critical harm to overall performance of the modpack so I'll leave it alone , until the issue is resolved by the mod author.

**Comment by Pythonic-Rainbow** [comment] 2018-09-06 09:06
EpicSquid is slowly updating the mod, however the progress is not optimistic.
This issue will be opened until the mod is dead or rewritten.

**Comment by Pythonic-Rainbow** [comment] 2019-04-03 09:41
Even the mod authors have no idea what was happening, and things changed a lot since then, I have no way to trace the bug. Sorry but this issue is unsolvable.

**Closed as completed by Pythonic-Rainbow** 2019-04-03 09:41 UTC
Labels: Cause: Mod Error, Type: Bug, unknown
